Fix for #46
wokalski/Diff.swift pull request #48
Opened 2017-03-08 13:38 UTC by farzadshbfn

I re-implemented LinkedList in a non-recursive format.

I also re-implemented DoublyLinkedList implementation with non-recursive format, but this relies on the fact that does compiler optimize calling of `array` on `LinkedList` because of it's `tail-recursion` or not.

2017-03-08 13:41 UTC, wokalski requested changes
Everything's awesome

2017-03-08 13:41 UTC, wokalski commented on Sources/LinkedList.swift
> +        let reversed = Array(array.reversed())
Maybe it's possible to use the result of `array.reversed()` directly?

2017-03-08 13:48 UTC, farzadshbfn commented on Sources/LinkedList.swift
> +        let reversed = Array(array.reversed())
Fixed it (thanks to your `Collection` extension)

2017-03-08 14:05 UTC, wokalski approved these changes

2017-03-08 19:08 UTC, wokalski commented
Travis is just super slow today 👎. I will merge (or you can) when CI is done.

Thank you for your contributions. This project would've been much worse without your help ✊

2017-03-09 05:35 UTC, merged

2017-03-17 05:38 UTC, farzadshbfn commented
🙏🏼🙏🏼